-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."softcartFactSales" DROP CONSTRAINT IF EXISTS itemsales;

ALTER TABLE IF EXISTS public."softcartFactSales" DROP CONSTRAINT IF EXISTS categoryitem;

ALTER TABLE IF EXISTS public."softcartFactSales" DROP CONSTRAINT IF EXISTS countrysales;

ALTER TABLE IF EXISTS public."softcartFactSales" DROP CONSTRAINT IF EXISTS datesales;



DROP TABLE IF EXISTS public."softcartDimDate";

CREATE TABLE IF NOT EXISTS public."softcartDimDate"
(
    dateid integer NOT NULL,
    month integer NOT NULL,
    "monthName" character(20) NOT NULL,
    day integer NOT NULL,
    "dayOfWeek" character(30) NOT NULL,
    year integer NOT NULL,
    "quarter " "char" NOT NULL,
    PRIMARY KEY (dateid)
);

DROP TABLE IF EXISTS public."softcartDimCategory";

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    categoryid integer NOT NULL,
    category character NOT NULL,
    PRIMARY KEY (categoryid)
);

DROP TABLE IF EXISTS public."softcartDimItem";

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    itemid integer NOT NULL,
    item character NOT NULL,
    PRIMARY KEY (itemid)
);

DROP TABLE IF EXISTS public."softcartDimCountry";

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    countryid integer NOT NULL,
    country character NOT NULL,
    PRIMARY KEY (countryid)
);

DROP TABLE IF EXISTS public."softcartFactSales";

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    salesid integer NOT NULL,
    itemid integer,
    categoryid integer,
    countryid integer,
    dateid integer,
    price numeric(10, 2),
    PRIMARY KEY (salesid)
);

ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT itemsales FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT categoryitem FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT countrysales FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT datesales FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;